ticket_dict = {'билет 1':'ticket/Билет 1.pdf', 'билет 2': 'ticket/Билет 2.pdf',
                'билет 3':'ticket/Билет 3.pdf', 'билет 4':'ticket/Билет 4.pdf',
                'билет 5':'ticket/Билет 5.pdf', 'билет 6':'ticket/Билет 6.pdf',
                'билет 7':'ticket/Билет 7.pdf', 'билет 8':'ticket/Билет 8.pdf',
                'билет 9':'ticket/Билет 9.pdf', 'билет 10':'ticket/Билет 10.pdf',
                'билет 11':'ticket/Билет 11.pdf', 'билет 12':'ticket/Билет 12.pdf',
                'билет 13':'ticket/Билет 13.pdf', 'билет 14':'ticket/Билет 14.pdf',
                'билет 15':'ticket/Билет 15.pdf', 'билет 16':'ticket/Билет 16.pdf',
                'билет 17':'ticket/Билет 17.pdf', 'билет 18':'ticket/Билет 18.pdf',
                'билет 19':'ticket/Билет 19.pdf', 'билет 20':'ticket/Билет 20.pdf',
                'билет 21':'ticket/Билет 21.pdf', 'билет 22':'ticket/Билет 22.pdf',
                'билет 23':'ticket/Билет 23.pdf', 'билет 24':'ticket/Билет 24.pdf',
                'билет 25':'ticket/Билет 25.pdf'} 

ticket_bel_dict = {'билет 1 б':'ticket_bel/Б1.pdf', 'билет 2 б': 'ticket_bel/Б2.pdf',
                'билет 3 б':'ticket_bel/Б3.pdf', 'билет 4 б':'ticket_bel/Б4.pdf',
                'билет 5 б':'ticket_bel/Б5.pdf', 'билет 6 б':'ticket_bel/Б6.pdf',
                'билет 7 б':'ticket_bel/Б7.pdf', 'билет 8 б':'ticket_bel/Б8.pdf',
                'билет 9 б':'ticket_bel/Б9.pdf', 'билет 10 б':'ticket_bel/Б10.pdf',
                'билет 11 б':'ticket_bel/Б11.pdf', 'билет 12 б':'ticket_bel/Б12.pdf',
                'билет 13 б':'ticket_bel/Б13.pdf', 'билет 14 б':'ticket_bel/Б14.pdf',
                'билет 15 б':'ticket_bel/Б15.pdf', 'билет 16 б':'ticket_bel/Б16.pdf',
                'билет 17 б':'ticket_bel/Б17.pdf', 'билет 18 б':'ticket_bel/Б18.pdf',
                'билет 19 б':'ticket_bel/Б19.pdf', 'билет 20 б':'ticket_bel/Б20.pdf',
                'билет 21 б':'ticket_bel/Б21.pdf', 'билет 22 б':'ticket_bel/Б22.pdf',
                'билет 23 б':'ticket_bel/Б23.pdf', 'билет 24 б':'ticket_bel/Б24.pdf',
                'билет 25 б':'ticket_bel/Б25.pdf'
}